### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by migueldelamo** [StevenSanz/STtoDoList#1]
Te he rechazado el proyecto, te pongo las líneas:
- https://github.com/StevenSanz/STtoDoList/blob/d086e33977775e0eda7d2afd9dfda3dffbfbfed3/src/js/Todolist.jsx#L18
- https://github.com/StevenSanz/STtoDoList/blob/d086e33977775e0eda7d2afd9dfda3dffbfbfed3/src/js/Todolist.jsx#L23

**Comment by StevenSanz** [comment]
fixeado
